package com.jm.sophon.engine.kubernetes.spark.config;

import io.fabric8.kubernetes.client.ConfigBuilder;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClientBuilder;

/**
 * TODO
 *
 * @Author jinmu
 * @Date 2023/9/28 17:05
 */
public class KubernetesClientAdapter {

    private KubernetesClient client;

    public KubernetesClientAdapter(){
        if(client == null ){
            init();
        }
    }

    public KubernetesClientAdapter(String k8sMasterUrl, String k8sCarCertData, String k8sClientCrtData, String K8sClientKeyData) {
        if(client == null){
            io.fabric8.kubernetes.client.Config config = new ConfigBuilder()
                    .withMasterUrl(k8sMasterUrl)
                    .withCaCertData(k8sCarCertData)
                    .withClientCertData(k8sClientCrtData)
                    .withClientKeyData(K8sClientKeyData)
                    .build();

            this.client = new KubernetesClientBuilder()
                    .withConfig(config)
                    .build();
        }
    }

    public void init() {
        String url = "https://192.168.217.140:6443";

        String carCertData = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXlOVEEzTkRZek5Wb1hEVE16TURVeU1qQTNORFl6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGVDClI4eUxPdVhKRmx4UWRyMWFXem5PNkJSQ3FUVTZSVmVlRXNRQlVJNVU1RnB3SVcxdTk2TGRGT2NrN2svSm1mQloKLyt4bFJRSDkrUjEvTGdtWUUzVkFmM3NNVUJGSk42b0E0NndVWmtjWnVnVnNaNVI5NXNUQ1o3Yk1lazNic2d0ZwpEUGZadzdMWnJmYURvNHhaRXVnRjBPNUtiOXdPQ1BmcnpSd2N2U1laUlFnMUJBU1ExYnJ3bi9sL2JuZmN3Mk1QCnNSUC9IS3dyWCtSSTFKYmZUdmdJV3prTzJ5WFJLSWsyamhEd1o2Z2dsZnZPRXBqS3UyQkpUWEh0L3pKZ3RITmYKZEE3WWZTQ0pNOExCT293K1NjRzBySFRlOHpFYTRKVHpjL2xzcVJnbjlaSDJ1VWIyNlZXOUJQTEJ5V0gycGxEVgpnL2xiVitEOGQyMm5YOXZJN0wwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJMGtDVGN0QzVPb2FZQmJKNVh6cEJ6VGdsRlhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBSkRCMHVFYmEvMTRmVFBjMi9taXE5TURmN0NZYUplUEUzWXZDMUpkZzV0UktKZWQ1dQo5ZGY5NWg0bXhmQTZLVFNzZU5JOFJrSzMrcGlDTnhvYjFHWXFuK3ZYWW1WOWhFdE9lcmhnd2k4YWdPVEN0eEl6CjRxK251R0I4amFtdU42bTV0WUt5YjZmQWNPM0ZtTWVLMXdrcU5sUHlYQTZCUzc5RVlSR0xpNEVNQ09VZEdIU3cKSU5WV3VneFBLYTRaNVFPZDZrWjZ6enFCQ0s2SlltN3NDbERwbmVQSDJETlRXZlJaNHJUZUlRdUNrbk5FTlRGMwpQMlVuaTFuQy9QdEtlOHJ4WEx4cE80WVloSDVhc0M0QUNuOTgvZWRDNG1JdEVtMjUvK0pkbHo3Ukh1WTZicURMCkFCdThxSFBoMXVxdjczeDl3c04rWUZBWjRhdTNFNUJRSFpJMQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg";
        String clientCrtData = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lRQkhibk04cjVSbGdmSWVKMHoxOFRwREFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEl6TURVeU5UQTNOVEV6TkZvWERUTXpNRFV5TWpBMwpORFl6TlZvd0VERU9NQXdHQTFVRUF4TUZZV1J0YVc0d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDYmM2bVJvc3N4QWRNZHZ3VldxMEl4SFh6RzdET2xWQzduYWxwMkIvaUJVbUhiMGIzVzkycEcKS0Zvb21KRkl2MjZGenJKc0NUbmdzUE5lUGdHUGhNTmU1M2lqMXJ3eFVFbmhMZmlWQzMyRTRoK2hsOHR5NVBSNgozRm11MDA4VUFuWFlSTEl6K3Z6ZW5vdXhEMVpDdzZjSEFMT3RXZVVzT2NYeS83SHE5dUR0OU0yblVQZjhlczJSCk1FWnhhOHBsQVo5OHcrclJvZ3UxRWh0eDhsaHJTZ3hxSGo3V1A1MnNXcHJHOVIvMHhkR2pVT0NFYk5tcEExeTMKaXdDcjB2dlNBeWpkbGIxOVp4eTg4aDRkL3BKOXRrQWR4RFRJd1pZYkp0Qk05N3RPTUJ5OUVWNkkxMS9XcXBTcwpqUlRhclBaMjNXUWdQN0JCRWtsVGJaWThLZDRpMWpCSEFnTUJBQUdqVmpCVU1BNEdBMVVkRHdFQi93UUVBd0lGCm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkSXdRWU1CYUEKRkkwa0NUY3RDNU9vYVlCYko1WHpwQnpUZ2xGWE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlZpZVFGS2RCYwp6b2srSEh3TkpwU1h2MlloMjhBSzhISm5Fa3lqRm50UEhzc0xPalNjdWltaWp6aHUxUElYdENjN042YjhFd2xMCjIwc1pMN2xqYVIrQU1YSzBvNDBIVVMvTmVSWnFJYmxBaWlwcjNJSnZNYlR0NGFtd2N6a21Jb0dZZ0taUmtBQ20KY2RycWUzcnRnTjdjSXZ1ekc0L2w3cjNydWU3UGhFOE5VaXZudlhqYjVCc29RWk1oWFN5b1NQSVV2ajAySGt4Tgp0SzUzU01GS3pMSklxMVRwRHdhYVdycGdXNURCNWRaWnNMMFVBRDJMN0JXaUlLcTFXeElkMEk5T0J4WUpOMFd1ClVMSTZNU2dId2p6enQvNStZOWlVcldiOEIyVDh5aDZXR1VIOWdtWTVKbGVzMVNKQi83bVRDaGFBZUdqSFpzUTEKTmRLYjVkN3FrczhECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K";
        String clientKeyData = "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbTNPcGthTExNUUhUSGI4RlZxdENNUjE4eHV3enBWUXU1MnBhZGdmNGdWSmgyOUc5CjF2ZHFSaWhhS0ppUlNMOXVoYzZ5YkFrNTRMRHpYajRCajRURFh1ZDRvOWE4TVZCSjRTMzRsUXQ5aE9JZm9aZkwKY3VUMGV0eFpydE5QRkFKMTJFU3lNL3I4M3A2THNROVdRc09uQndDenJWbmxMRG5GOHYreDZ2Ymc3ZlROcDFEMwovSHJOa1RCR2NXdktaUUdmZk1QcTBhSUx0UkliY2ZKWWEwb01haDQrMWorZHJGcWF4dlVmOU1YUm8xRGdoR3paCnFRTmN0NHNBcTlMNzBnTW8zWlc5ZldjY3ZQSWVIZjZTZmJaQUhjUTB5TUdXR3liUVRQZTdUakFjdlJGZWlOZGYKMXFxVXJJMFUycXoyZHQxa0lEK3dRUkpKVTIyV1BDbmVJdFl3UndJREFRQUJBb0lCQVFDTzRDaXJOWEFDRkFaQgpJYys3VDk2Zm05V1NVNGhJWFc1YXZoSjB4M0N0RTlYam53d1g1d0VqaUhVTk9PVFhjek1YQXRwVWw4bzliUVhSCnliWFBmaHUvUDRwUE04OTJsNisvcW12K09UaGRpU08vZHUvRUl4RmRWdWVLMnFhazRub0RrMmdpaEg0ajhwNjcKMXpmV1YxTk9DV1FiWVROVWlha1paYy9XQUtETnN6TGU3bCtKcEJydU9HbUdHS0l0T1Fkc1FpVmliUlpycHNhUQo5YW5JOTNJTXVvK1VCMnBhMDRHUlZPTnpCSzVHUldSL0RwU0ZVUlJHTkg5WFJRNGRzYnlvZjRZMkZVWFRIdlljCk42aTVXU0tDS3A0M2xJcUMzMzJ2TjlFVHoyZlJ2K0JyN1MwLzVlc0tpVEZHdWpicG9iRFJ5bS9Ec1VzZFQwWjgKZmJiNkRpUXhBb0dCQU02anRuMk5VR21yZXdsSnRsSzRWb1hFTkFOVVkvaDBlZU5uUkxRMkZsTjNmNnFMSmVLTQovTTAvK085bFNoMlJSNTBIV29UOW83TEdaU2xZa2dlMVJzTWppM2ljQjNzUWdQeGg3bVp2SVdOSUY4V0htc0VhCmExRHZ3Q003YzZaOVB0bENjUlFzTnNOY2ZwYjY3Nno0blpUWDdQc3l0cVJMbS92bUVIRnF0M3k1QW9HQkFNQ1YKd0lvWmlhWFRsSVgzODJGd1lZVjRjcm1pSVhLZGlxNkNCc0hIOGg1NjRIUUtyS3BRQ3VFRzdoZmlvRFczc004VwpTd1BiRUp0UDdKdW0wdzhqb21QV3RjRWZkY1pJRjJJVExsc2lhSStmamFNbWtaODJmSllhWExtbmVOdkFmQWxFCnkzZHcwMThBa2x5MUNIbkphOHFQQm53cUxhb2NhcjJRMUZueXBwVC9Bb0dBQ2tLS3J4VXpKdXdDd2VWTkRqSmsKNldOaWliL0k3dThwbGlic2ZGNHJJWjNQVXZKeHdSdnErVzN4dUVFNU90cVp5YXd4ekdTam1oN0xxdy9nd0UwNQo1RHFCbEUxNitadEtMRDNZam5GNklPblZkRk5WVmIwd0V1YTBqWXRJSkw0WFBzWlR3d0ttL1hBOFFOYll5NmZVCmV5MTFjTXVGMGdhSENpelVLQzE2U3RFQ2dZQUJiTnBJNjFsMmJiTnFybVFSczRnMU9hZjNzYmgzcGF6U0Q4cEgKQXRqSzJ2UHdSK2Z4TnJodDQrUTlMd01xZ3BwL1hkWGVTRysrQm9Ca3duNUxYV01sUkFDQ1ZsNUR3bUxSNmZ4cwoxanRaM0w5cWxxMTdOU2NFNFZzUVVLbjNUbHhjb1RLMFJwUjUzb0kyeDJ3eG9vajJyY3BKZnZKcGtONUZXdDRICmNHRkZOd0tCZ1FERlp6b3ljTXR1cDhzUUZUcEVsVU5WMkZ5RkFLUTk1VWwrMnJZTTJwTDl2L2V3ak44YzllNVIKTG5pTldVek4vZWlCVnBqR24xb0psRERYK3hxYWJTeWF6dnBIcVFwVjVsTlFKNVRYMGoxQ0Y1aUZEbkxBSS9VbwpodjFIZW1xVjVsOERZWUVVZkhhbUQyTVhXWHFTSlBuQVd3OTlKMTlUeWhIaWZMeWh1eEpOTEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo";


        io.fabric8.kubernetes.client.Config config = new ConfigBuilder()
                .withMasterUrl(url)
                .withCaCertData(carCertData)
                .withClientCertData(clientCrtData)
                .withClientKeyData(clientKeyData)
                .build();

        this.client = new KubernetesClientBuilder()
                .withConfig(config)
                .build();

    }

    public void closeKubernetesClient() {
        if (this.client != null) {
            this.client.close();
        }
    }

    public KubernetesClient getClient() {
        return client;
    }
}
